In [2]:
import pandas as pd
import numpy as np
import seaborn as s
import matplotlib.pyplot as p

In [3]:
data=pd.read_csv(r"C:\Users\SPTINT-21\Desktop\Mall_Customers.csv")
df=pd.DataFrame(data)

In [4]:
df.describe()

       CustomerID         Age  Annual-Income  Spending-Score
count  220.000000  220.000000     220.000000      220.000000
mean   102.281818   38.877273      62.109091       50.086364
std     61.926475   13.975792      29.526351       27.139868
min      1.000000   18.000000      15.000000        1.000000
25%     47.750000   29.000000      40.000000       29.000000
50%    102.500000   36.000000      62.000000       50.000000
75%    157.250000   49.000000      78.000000       73.000000
max    200.000000   70.000000     137.000000       99.000000

In [7]:
stud=pd.read_csv(r"C:\Users\SPTINT-21\Desktop\students.csv")
print(stud.head(10))

   student_id  age  percentage employeed
0           1   19          80       yes
1           2   20          60        no
2           3   18          52        no
3           4   21          42        no
4           5   19          58        no
5           6   24          80       yes
6           7   22          90       yes
7           8   21          91       yes
8           9   24          58       yes
9          10   23          45        no

In [8]:
marks=pd.read_csv(r"C:\Users\SPTINT-21\Desktop\marks.csv")
print(marks.head(10))

   marks      city  student_id
0     85    tumkur           1
1     92  banglore           2
2     88   chennai           3
3     97    vellor           4
4     45    mysore           5

In [9]:
df=pd.merge(stud,marks)
print(df.head(10))

   student_id  age  percentage employeed  marks      city
0           1   19          80       yes     85    tumkur
1           2   20          60        no     92  banglore
2           3   18          52        no     88   chennai
3           4   21          42        no     97    vellor
4           5   19          58        no     45    mysore

In [10]:
df

   student_id  age  percentage employeed  marks      city
0           1   19          80       yes     85    tumkur
1           2   20          60        no     92  banglore
2           3   18          52        no     88   chennai
3           4   21          42        no     97    vellor
4           5   19          58        no     45    mysore

In [15]:
tutors=["shilpa","veena","vani","roopa","shilpa"]
college=["sit","spt","sit","spt","sit"]

In [16]:
len(df['student_id'])

5

In [17]:
add=df.assign(totursassigned=tutors,collagename=college)
print(add)

   student_id  age  percentage employeed  marks      city totursassigned  \
0           1   19          80       yes     85    tumkur         shilpa
1           2   20          60        no     92  banglore          veena
2           3   18          52        no     88   chennai           vani
3           4   21          42        no     97    vellor          roopa
4           5   19          58        no     45    mysore         shilpa

  collagename
0         sit
1         spt
2         sit
3         spt
4         sit

In [18]:
total=[450,600,467,567,560]
new=add.assign(totalmarks=total)

In [19]:
df

   student_id  age  percentage employeed  marks      city
0           1   19          80       yes     85    tumkur
1           2   20          60        no     92  banglore
2           3   18          52        no     88   chennai
3           4   21          42        no     97    vellor
4           5   19          58        no     45    mysore

In [20]:
add

,student_id,age,percentage,employeed,marks,city,totursassigned,collagename
0,1,19,80,yes,85,tumkur,shilpa,sit
1,2,20,60,no,92,banglore,veena,spt
2,3,18,52,no,88,chennai,vani,sit
3,4,21,42,no,97,vellor,roopa,spt
4,5,19,58,no,45,mysore,shilpa,sit

In [21]:
new

,student_id,age,percentage,employeed,marks,city,totursassigned,collagename,totalmarks
0,1,19,80,yes,85,tumkur,shilpa,sit,450
1,2,20,60,no,92,banglore,veena,spt,600
2,3,18,52,no,88,chennai,vani,sit,467
3,4,21,42,no,97,vellor,roopa,spt,567
4,5,19,58,no,45,mysore,shilpa,sit,560

In [22]:
new=new.assign(percantage=lambda x: new.totalmarks *100 /600)
print(new)

   student_id  age  percentage employeed  marks      city totursassigned  \
0           1   19          80       yes     85    tumkur         shilpa
1           2   20          60        no     92  banglore          veena
2           3   18          52        no     88   chennai           vani
3           4   21          42        no     97    vellor          roopa
4           5   19          58        no     45    mysore         shilpa

  collagename  totalmarks  percantage
0         sit         450   75.000000
1         spt         600  100.000000
2         sit         467   77.833333
3         spt         567   94.500000
4         sit         560   93.333333

In [23]:
new=new.assign(a=None,b=0)
print(new)

   student_id  age  percentage employeed  marks      city totursassigned  \
0           1   19          80       yes     85    tumkur         shilpa
1           2   20          60        no     92  banglore          veena
2           3   18          52        no     88   chennai           vani
3           4   21          42        no     97    vellor          roopa
4           5   19          58        no     45    mysore         shilpa

  collagename  totalmarks  percantage     a  b
0         sit         450   75.000000  None  0
1         spt         600  100.000000  None  0
2         sit         467   77.833333  None  0
3         spt         567   94.500000  None  0
4         sit         560   93.333333  None  0

In [24]:
new1=new.insert(1,"tutors_indexing",tutors)
print(new)

   student_id tutors_indexing  age  percentage employeed  marks      city  \
0           1          shilpa   19          80       yes     85    tumkur
1           2           veena   20          60        no     92  banglore
2           3            vani   18          52        no     88   chennai
3           4           roopa   21          42        no     97    vellor
4           5          shilpa   19          58        no     45    mysore

  totursassigned collagename  totalmarks  percantage     a  b
0         shilpa         sit         450   75.000000  None  0
1          veena         spt         600  100.000000  None  0
2           vani         sit         467   77.833333  None  0
3          roopa         spt         567   94.500000  None  0
4         shilpa         sit         560   93.333333  None  0