In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as p
import seaborn as s
from sklearn.model_selection import train_test_split as t

In [35]:
x=np.arange(1,25).reshape(12,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [36]:
y=np.array([0,1,1,0,1,0,1,0,1,1,0,1])
y

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1])

In [37]:
x_train, x_test, y_train, y_test =t(x,y,test_size=4,random_state=4)

In [38]:
x_train

array([[17, 18],
       [ 5,  6],
       [23, 24],
       [ 1,  2],
       [ 3,  4],
       [11, 12],
       [15, 16],
       [21, 22]])

In [39]:
x_test

array([[ 7,  8],
       [ 9, 10],
       [13, 14],
       [19, 20]])

In [40]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 0])

In [41]:
y_test

array([0, 1, 1, 1])

In [42]:
data=pd.read_csv(r"C:\Users\SPTINT-21\Downloads\Iris (1).csv")

In [43]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [44]:
data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [45]:
data_x=data.drop(["Species","Id"],axis=1)

In [46]:
data_x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [47]:
data_y=data['Species']
data_y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: str

In [48]:
x_train, x_test, y_train, y_test=t(data_x,data_y)

In [49]:
x_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
69             5.6           2.5            3.9           1.1
114            5.8           2.8            5.1           2.4
22             4.6           3.6            1.0           0.2
63             6.1           2.9            4.7           1.4
20             5.4           3.4            1.7           0.2
..             ...           ...            ...           ...
65             6.7           3.1            4.4           1.4
66             5.6           3.0            4.5           1.5
73             6.1           2.8            4.7           1.2
59             5.2           2.7            3.9           1.4
112            6.8           3.0            5.5           2.1

[112 rows x 4 columns]

In [50]:
x_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
43             5.0           3.5            1.6           0.6
91             6.1           3.0            4.6           1.4
45             4.8           3.0            1.4           0.3
124            6.7           3.3            5.7           2.1
14             5.8           4.0            1.2           0.2
15             5.7           4.4            1.5           0.4
107            7.3           2.9            6.3           1.8
16             5.4           3.9            1.3           0.4
119            6.0           2.2            5.0           1.5
131            7.9           3.8            6.4           2.0
93             5.0           2.3            3.3           1.0
138            6.0           3.0            4.8           1.8
37             4.9           3.1            1.5           0.1
27             5.2           3.5            1.5           0.2
95             5.7           3.0            4.2           1.2
141            6.9           3.1            5.1           2.3
50             7.0           3.2            4.7           1.4
44             5.1           3.8            1.9           0.4
120            6.9           3.2            5.7           2.3
52             6.9           3.1            4.9           1.5
110            6.5           3.2            5.1           2.0
98             5.1           2.5            3.0           1.1
82             5.8           2.7            3.9           1.2
23             5.1           3.3            1.7           0.5
30             4.8           3.1            1.6           0.2
18             5.7           3.8            1.7           0.3
108            6.7           2.5            5.8           1.8
84             5.4           3.0            4.5           1.5
67             5.8           2.7            4.1           1.0
10             5.4           3.7            1.5           0.2
134            6.1           2.6            5.6           1.4
99             5.7           2.8            4.1           1.3
140            6.7           3.1            5.6           2.4
7              5.0           3.4            1.5           0.2
92             5.8           2.6            4.0           1.2
94             5.6           2.7            4.2           1.3
75             6.6           3.0            4.4           1.4
4              5.0           3.6            1.4           0.2

In [51]:
y_train

69     Iris-versicolor
114     Iris-virginica
22         Iris-setosa
63     Iris-versicolor
20         Iris-setosa
            ...
65     Iris-versicolor
66     Iris-versicolor
73     Iris-versicolor
59     Iris-versicolor
112     Iris-virginica
Name: Species, Length: 112, dtype: str

In [52]:
y_test

43         Iris-setosa
91     Iris-versicolor
45         Iris-setosa
124     Iris-virginica
14         Iris-setosa
15         Iris-setosa
107     Iris-virginica
16         Iris-setosa
119     Iris-virginica
131     Iris-virginica
93     Iris-versicolor
138     Iris-virginica
37         Iris-setosa
27         Iris-setosa
95     Iris-versicolor
141     Iris-virginica
50     Iris-versicolor
44         Iris-setosa
120     Iris-virginica
52     Iris-versicolor
110     Iris-virginica
98     Iris-versicolor
82     Iris-versicolor
23         Iris-setosa
30         Iris-setosa
18         Iris-setosa
108     Iris-virginica
84     Iris-versicolor
67     Iris-versicolor
10         Iris-setosa
134     Iris-virginica
99     Iris-versicolor
140     Iris-virginica
7          Iris-setosa
92     Iris-versicolor
94     Iris-versicolor
75     Iris-versicolor
4          Iris-setosa
Name: Species, dtype: str